In [49]:
import pandas as pd
import plotly.express as px
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as sci

In [50]:
# test = pd.read_csv("C:/Users/Avery/Documents/GitHub/Regression_proj/dsProject/test_sample.csv")
train = pd.read_csv("C:/Users/Avery/Documents/GitHub/Regression_proj/dsProject/train_sample.csv")
train.drop(columns='Unnamed: 0',inplace= True)

for i in range(1,10):
    train['M'+str(i)] = train['M'+str(i)].replace({'T': 1, 'F': 0})



In [51]:
transactions = train[train['TransactionAmt'] >0 ]['TransactionAmt']

# Dist of TransactionAmt
fig = px.histogram(
    transactions, 
    title= "Distribuiton of Transactions",
    nbins=1000
    ) 

fig.update_layout( height=500, width=1000)
fig.update_xaxes(range = [0,5000])

In [52]:
Card_Dist = pd.value_counts(train['card4'],normalize= True, dropna = False)

# Dist of Card Types
fig = px.bar( 
    data_frame = Card_Dist,
    title='Distribution of Card Type',color = Card_Dist.keys(),
    text= Card_Dist.apply(lambda x: f'{x*100:.2f}%'),
    orientation='h'
    )

fig.update_layout(xaxis={'title': 'Card Types'},yaxis={'title': 'Percentage'}, height=500, width=1000)

In [53]:
dist = pd.value_counts(train['DeviceInfo'],normalize= True, dropna = False)

amount_to_show = 9
new_data = {}

for i, (key, value) in enumerate(dist.to_dict().items()):
    if i < amount_to_show:
        new_data[key] = value
    else:
        new_data['Other'] = new_data.get('Other', 0) + value

fig = px.pie(
    values=list(new_data.values()), 
    names=list(new_data.keys()),
    title= 'Distribution Of Operating System That Made The Transaction'
    )

# fig.update_layout(height=500, width=750,showlegend = False)
fig.update_traces(textinfo='percent+label')
fig.show()

In [54]:
proplist = [1,2,3,5,6,7,8,9]

for i in proplist:
    prop = train['M'+str(i)].mean()
    print(f'prop of M{i} = {prop}')

prop of M1 = 0.9999376111301744
prop of M2 = 0.8945940044296098
prop of M3 = 0.7876282871135789
prop of M5 = 0.45392434594234293
prop of M6 = 0.4594882982002703
prop of M7 = 0.13530509574813374
prop of M8 = 0.36524808308653495
prop of M9 = 0.8423871150959471


In [55]:
for col, values in train.iteritems():
    num_uniques = values.nunique()
    print ('{name}: {num_unique}'.format(name=col, num_unique=num_uniques))
    print (values.unique())
    print ('\n')

TransactionID: 59054
[3492343 3371844 3084671 ... 3245562 3338546 3019864]


isFraud: 2
[0 1]


TransactionDT: 58877
[13223795  9653067  1979646 ...  6204072  8668272   829558]


TransactionAmt: 5671
[ 58.95  507.95  250.    ... 891.95   78.909  94.925]


ProductCD: 5
['W' 'R' 'C' 'H' 'S']


card1: 6171
[ 2772  4112  4436 ...  3013  5509 12572]


card2: 500
[512. 390. 174. 357. 321. 111. 194. 204. 555. 375. 553. 481.  nan 545.
 547. 215. 514. 490. 122. 408. 452. 268. 310. 355. 381. 583. 130. 302.
 298. 586. 300. 225. 327. 170. 264. 361. 249. 455. 454. 399. 410. 266.
 513. 158. 480. 562. 343. 181. 360. 470. 356. 453. 241. 567. 283. 199.
 559. 404. 396. 382. 520. 584. 393. 422. 332. 100. 461. 549. 253. 269.
 445. 501. 369. 312. 432. 104. 296. 534. 206. 103. 345. 548. 142. 250.
 500. 543. 594. 440. 402. 101. 479. 376. 528. 525. 420. 236. 106. 588.
 476. 131. 494. 177. 554. 558. 203. 431. 539. 533. 482. 231. 127. 517.
 314. 141. 165. 387. 449. 188. 119. 418. 593. 417. 540. 412. 346. 322.
 

In [56]:
print('hi')

hi
